on: push
name: Deploy api on push
jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Getting latest code
        uses: actions/checkout@v2

      - name: Deploy to sandbox via rsync
        uses: trendyminds/github-actions-rsync@master
        env:
          SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
          SSH_USERNAME: ${{secrets.SSH_USERNAME}}
          SSH_HOSTNAME: ${{secrets.SSH_HOSTNAME}}

      - name: Installing Node - v16.14.0
        uses: actions/setup-node@v1.4.1
        with:
          node-version: "16.14.0"
      - name: Installing dependencies...
        uses: jaid/action-npm-install@v1.2.1

      - name: Running application
        run: npm start
